// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// DATABASE CONNECTION DISABLED - Using empty database
// export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Mock supabase client for empty database mode
export const supabase = null as any;